import logging
from raser.supports.output import output

def main(kwargs):

    #CEPC fast lumi at IP downstream 10m(Position 1)

    label = kwargs['label']
    verbose = kwargs['verbose'] 

    if verbose == 1: # -v 
        logging.basicConfig(level=logging.INFO)
    if verbose == 2: # -vv 
        logging.basicConfig(level=logging.DEBUG)

    logging.info('This is INFO messaage')
    logging.debug('This is DEBUG messaage')

    if label == 'pe_dis':  # primary electrons distribution, XoY plane and Z direction
       from . import data_file
       data_file.main()

    if label == 'spd_dis': #simulation secondary particles distribution at 31mm and -31mm plane, Y direction and Z direction 
       from . import spd_dis
       spd_dis.main()

    if label == 'spd_dis_plot': #plot the secondary particles distribution
       from . import spd_plot
       spd_plot.main()

    if label == 'np_precision_plot':   # The number of detected Bhabha electrons and corresponding relative precision vs different vertical length and current threshold
       from . import np_precision_plot
       np_precision_plot.main()
       
    if label == 'lumi_fit':  # TSC vs lumi ratio plot
       from . import lumi_TSC_precision_fit
       lumi_TSC_precision_fit.main()

    if label == 'Amp_dis':     # The amplitude of 2 entire detectors within 1 ms, nominial lumi and 10% nominial lumi
       from . import amplitude_dis
       amplitude_dis.main()

    if label == 'bunch_number':  #The number of bunches which current signal over threshold(0, 0.05, 0.5, 1, 3, 5). Check input!
       from . import bunch_number
       bunch_number.main()

    if label == 'p1_sample': #Generate Poisson distribution at position 1. Check output path
       from . import p1_sample
       p1_sample.main()

    if label == 'current':  # Generate current signal
       from . import get_current_p1
       get_current_p1.main(output(__file__, "test")) 

    if label == 'DAQ_sim':      # DAQ simulation and generate TSC value
       from . import DAQ_system_sim
       DAQ_system_sim.main()
       
    if label == 'Pixel_current': # Simulate the current generated by detector_I_0_1 at N0=3.4 or N0=0.34, depend on the input output_path
       from . import pixel_current_plot
       pixel_current_plot.main(output(__file__, "N0_3_4"), '340')
